name: "Hello World"
description: "A simple hello world action demonstrating TypeScript without ncc"
inputs:
  name:
    description: "Name to greet"
    required: false
    default: "World"
outputs:
  greeting:
    description: "The greeting message"
runs:
  using: "node20"
  main: "./index.js"