name: Generate Badges

on:
  workflow_dispatch:

jobs: 
  generate-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Badges
        id: badges
        uses: ./badges
        with:
          auth-token: ${{secrets.TEMP_DEV_PAT}}
          markdown: README.md

